### PR TITLE
CLOUDOPS-512 : Add cnonce and nc to Auth header

### LINKED ISSUE #14: Missing cnonce in getAuthorization
Hello, 

I was trying to use SIPunit 2.0.1 to do a simple REGISTER test and found out that the cnonce and nc-value fields in the Authenticate Header are not implemented, as we can see below. 

See here directly in the code: https://github.com/RestComm/sipunit/blob/011a01f0b3712071d661a54a43cb6b3048764c5f/src/main/java/org/cafesip/sipunit/SipSession.java#L1699

Sorry for the formatting below: 
`public AuthorizationHeader getAuthorization(String method, String uri, String requestBody,
      WWWAuthenticateHeader authHeader, String username, String password) throws SecurityException {
    String response = null;
    try {
      response = MessageDigestAlgorithm.calculateResponse(authHeader.getAlgorithm(), username,
          authHeader.getRealm(), new String(password), authHeader.getNonce(),
          // TODO we should one day implement those two null-s
          null, // nc-value
          null, // cnonce
          method, uri, requestBody, authHeader.getQop());
    } catch (NullPointerException exc) {
      throw new SecurityException(
          "The received authenticate header was malformatted: " + exc.getMessage());
    }`

Using these values is actually a required to authenticate in my case and would block any use of SIPunit I want to make. Is there any plan on addressing this? 

Thank you.

### PR DESCRIPTION
**Pull request by abdulazizali77**
Fixes https://github.com/RestComm/sipunit/issues/14
Will fix testsuite of https://github.com/RestComm/Restcomm-Connect/pull/2404

### CODE REVIEW

**Comment by abdulazizali77** [comment]
```
Failed tests:   testWaitForAuthPositive(org.cafesip.sipunit.test.noproxy.TestNoProxy)
  testWaitForAuthPositive(org.cafesip.sipunit.test.noproxy.TestNoProxyTLS)
  testEndSubscription(org.cafesip.sipunit.test.noproxy.TestPresenceNoProxy)
  testBadInput2(org.cafesip.sipunit.test.noproxy.TestReferNoProxy): Expected exception: java.text.ParseException
  testBadInput3(org.cafesip.sipunit.test.noproxy.TestReferNoProxy): Expected exception: java.text.ParseException
  testErrorSubscribeResponseNoExpiry(org.cafesip.sipunit.test.noproxy.TestReferNoProxy)

Tests run: 114, Failures: 6, Errors: 0, Skipped: 2
```
Have not analyzed failures. Might be Windows specific

**Comment by jaimecasero** [comment]
@abdulazizali77 the change seems fair. Bear in mind most of the times the tests are weak, and sometimes they fail for different reasons ("address already in use" , some timing condition...), so its better to execute the CI job and make sure about the new failing tests...

**Comment by abdulazizali77** [comment]
@jaimecasero Thanks for reviewing Jaime, i ran the CI job which is doing a build for all branches. Seems to be failing at the moment. Do you think i should create a new CI specific for the new branch or what would you advise?

**Comment by jaimecasero** [comment]
the initial code was causing two tests to fail, after latest commit checking null, those tests are passed correctly. I think this is ready to merge

**Pull request merged**
