### PR TITLE
Features/conference event

### PR DESCRIPTION
**Pull request by pimenas**
This pull requests makes 2 small changes
1. fixes 3 invalid javadoc comments
2. adds support for testing 'conference' events, using waitRequest()

I haven't added any tests, I'm open if you think I should implement something different for supporting 'conference' events.

### CODE REVIEW

**Comment by deruelle** [comment]
Thanks @pimenas Can you sign the contributor License agreement at http://www.telestax.com/open-source/#Contribute so we can accept the Pull Request and acknowledge your contribution ?

Also I think it would make sense to add a test for conference events to show it's working well

**Comment by pimenas** [comment]
Hi Jean,

I just signed the license, and now I'm thinking about the testing. I think
it will be better to create a separate file e.g. TestConferenceNoProxy.java
and put everything related to conferences there, which is currently not
much :(.

Kind regards,
Epi

Epimenidis Voutsakis
Electronics & Computer Engineer
pimenas@gmail.com
+30 695 720 6307 (Mobile, Greece)

**Comment by deruelle** [comment]
Thanks @pimenas. The solution you propose sounds good to me, we can add more tests to it as more use cases come up

**Comment by deruelle** [comment]
Please make sure to add the license header from https://docs.google.com/document/d/1RZz2nd2ivCK_rg1vKX9ansgNF6NpK_PZl81GxZ2MSnM/edit#heading=h.iayg4mgzyzs8 to each new Java file. Thanks !

**Comment by gvagenas** [comment]
Thanks for the pr @pimenas , will review and merge as soon as possible.

**Comment by deruelle** [comment]
@pimenas yes please create a new TestConferenceNoProxy file we can add to it as we move forward.

**Comment by pimenas** [comment]
Added the test, please check if it's ok

**Comment by deruelle** [comment]
@pimenas can you please make sure to add the license header from https://docs.google.com/document/d/1RZz2nd2ivCK_rg1vKX9ansgNF6NpK_PZl81GxZ2MSnM/edit#heading=h.iayg4mgzyzs8 for the test as well ?

**Comment by deruelle** [comment]
Thanks @pimenas ! Acknowledged at https://telestax.com/acknowledgements/

**Comment by pimenas** [comment]
You're welcome @deruelle @gvagenas !

**Pull request merged**
